import { EnvelopeIcon, ArrowLongRightIcon } from '@heroicons/react/20/solid';
import Head from 'next/head';
import Image from 'next/image';
import Example from '../components/navbar';

export default function Home() {
  const products = [
    {
      id: 1,
      name: 'Leather Long Wallet',
      color: 'Natural',
      price: '$75',
      href: '/products/leather-long-wallet',
      imageSrc:
        'https://tailwindui.com/img/ecommerce-images/home-page-04-trending-product-02.jpg',
      imageAlt: 'Hand stitched, orange leather long wallet.',
    },
    {
      id: 1,
      name: 'Valet Tray',
      color: 'Natural',
      price: '$79',
      href: '/products/valet-tray',
      imageSrc:
        'https://cdn.shopify.com/s/files/1/0167/4484/products/valet-maple-med-1_1480x1836_crop_center.jpg?v=1636495414',
      imageAlt: 'Solid maple tray with matte finish',
    },
    {
      id: 1,
      name: `Men's Essential Tee`,
      color: 'Black',
      price: '$22.40',
      href: '/products/mens-essential-tee',
      imageSrc:
        'https://cdn.shopify.com/s/files/1/0167/4484/products/essnetial-black-1_1480x1836_crop_center.jpg?v=1560367417',
      imageAlt: 'Solid black cotton tee',
    },
    // More products...
  ];

  return (
    <div className="flex justify-center">
      <Head>
        <title>storefront.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <Example />
        <div className="max-w-5xl px-8 mx-auto pt-16 pb-32 grid grid-flow-col gap-24 items-center">
          <div>
            <h1 className="text-6xl font-semibold">A cool and short slogan.</h1>
            <p className="my-8 text-xl text-zinc-600 font-light">
              A diam sollicitudin tempor id eu nisl. Ultrices in iaculis nunc
              sed augue lacus viverra vitae. In nulla posuere sollicitudin
              aliquam ultrices sagittis orci a.
            </p>
            <button
              type="button"
              className="inline-flex items-center rounded-md border border-transparent bg-black px-6 py-3 text-base font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
            >
              Shop Now
              <ArrowLongRightIcon
                className="ml-2 -mr-1 h-5 w-5"
                aria-hidden="true"
              />
            </button>
          </div>
          <div className="relative">
            <img
              className="rotate-[-10deg] h-[500px] border-4 border-white shadow-lg w-full justify-end rounded-2xl object-center object-cover"
              src="https://images.pexels.com/photos/3522562/pexels-photo-3522562.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
            ></img>
            <img
              className="absolute top-0 left-0 h-[500px] border-4 border-white shadow-lg w-full justify-end rounded-2xl object-center object-cover"
              src="https://images.pexels.com/photos/5727889/pexels-photo-5727889.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
            ></img>
            <img
              className="absolute top-0 left-0 rotate-[10deg] h-[500px] border-4 border-white shadow-lg w-full justify-end rounded-2xl object-center object-cover"
              src="https://images.pexels.com/photos/263877/pexels-photo-263877.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
            ></img>
          </div>
        </div>
        <div className="bg-zinc-100 flex justify-center">
          <div className="text-center max-w-xl py-24 flex flex-col items-center">
            <h2 className="text-3xl">About Us</h2>
            <p className="py-3 text-zinc-700 text-lg font-light">
              A diam sollicitudin tempor id eu nisl. Ultrices in iaculis nunc
              sed augue lacus viverra vitae. In nulla posuere sollicitudin
              aliquam ultrices sagittis orci a.
            </p>
            <p className="py-3 text-zinc-700 text-lg">With love,</p>
            <img
              className="h-32 justify-self-center self-center"
              src="https://www.signwell.com/assets/vip-signatures/marilyn-monroe-signature-7fff246e7835644c8d4b11d60ed1fb965b4ef778f476f3f543904e6fdf1237b7.svg"
            />
          </div>
        </div>
        <div className="bg-white">
          <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-5xl lg:px-8">
            <div className="md:flex md:items-center md:justify-between">
              <h2 className="text-2xl font-bold tracking-tight text-gray-900">
                Trending products
              </h2>
              <a
                href="#"
                className="hidden text-sm font-medium text-indigo-600 hover:text-indigo-500 md:block"
              >
                Shop the collection
                <span aria-hidden="true"> &rarr;</span>
              </a>
            </div>

            <div className="mt-6 grid grid-cols-2 gap-x-4 gap-y-10 sm:gap-x-6 md:grid-cols-3 md:gap-y-0 lg:gap-x-8">
              {products.map((product) => (
                <div key={product.id} className="group relative">
                  <div className="h-56 w-full overflow-hidden rounded-md bg-gray-200 group-hover:opacity-75 lg:h-72 xl:h-80">
                    <img
                      src={product.imageSrc}
                      alt={product.imageAlt}
                      className="h-full w-full object-cover object-center"
                    />
                  </div>
                  <h3 className="mt-4 text-sm text-gray-700">
                    <a href={product.href}>
                      <span className="absolute inset-0" />
                      {product.name}
                    </a>
                  </h3>
                  <p className="mt-1 text-sm text-gray-500">{product.color}</p>
                  <p className="mt-1 text-sm font-medium text-gray-900">
                    {product.price}
                  </p>
                </div>
              ))}
            </div>

            <div className="mt-8 text-sm md:hidden">
              <a
                href="#"
                className="font-medium text-indigo-600 hover:text-indigo-500"
              >
                Shop the collection
                <span aria-hidden="true"> &rarr;</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
